import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Button } from "@/components/ui/button";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 p-4`}
    >
    <header className="flex justify-between items-center mb-8">
      <Link href="/">
        <div className="text-3xl font-bold text-red-700 cursor-pointer">CS-CODER</div>
      </Link>
      <Button className="bg-white text-red-700 shadow-neumorphic transition-shadow">
        Login
      </Button>
    </header>
    {children}
    </body>
    </html>
  );
}
